"""The circuit as a place, and the cars on it.

The engine's physics is a distance model and stays one; this layer is the other
half of a race -- where those distances are, what is either side of the road,
and what happens when two cars want the same piece of it.

These are the checks the layer was asked for: a straight, a corner, a road that
changes width, a collision, the pit lane, and the same seed giving the same
world twice.
"""

from __future__ import annotations

import math

import pytest

from f1_race_engine import load_track
from f1_race_engine.world import Surface, build_world
from f1_race_engine.world.body import CAR_LENGTH, CAR_WIDTH, CarBody
from f1_race_engine.world.collision import against_wall, overlap, resolve
from f1_race_engine.world.geometry import Vec2, closest_point_on_segment
from f1_race_engine.world.space import Grid
from f1_race_engine.world.step import World


@pytest.fixture(scope="module")
def world():
    return build_world(load_track("bahrain"))


# -- the road ------------------------------------------------------------------


def test_the_centreline_advances_everywhere(world):
    """A polyline that stands still has no direction to be offset along, and
    every edge, kerb and wall is generated by offsetting it."""
    steps = [
        (world.centre[i + 1] - world.centre[i]).length
        for i in range(len(world.centre) - 1)
    ]

    assert min(steps) > 0.0, "two samples in the same place"
    # Not evenly spaced, and it should not be.  The samples are laid out by
    # distance along the *racing line*, and the road is that line pushed
    # sideways -- so round the outside of a corner the road covers more ground
    # between two samples than the line does.  What matters is that it always
    # covers some and never doubles back.
    assert max(steps) < world.step * 1.5


def test_a_straight_is_flanked_by_grass_and_then_a_wall(world):
    """Nobody builds a gravel trap down the side of a straight."""
    at = next(i for i, corner in enumerate(world.corners) if not corner) * world.step
    half = world.half_width[world.sample_of(at)]

    assert world.surface_at(world.place(at, 0.0)[0]) is Surface.TRACK
    assert world.surface_at(world.place(at, half - 0.5)[0]) is Surface.TRACK
    assert world.surface_at(world.place(at, half + 1.0)[0]) is Surface.GRASS
    assert world.surface_at(world.place(at, half + 30.0)[0]) is Surface.BARRIER


def test_a_corner_has_a_kerb_then_tarmac_then_gravel(world):
    """The order a car leaving the road at a corner meets things in."""
    at = next(i for i, corner in enumerate(world.corners) if corner) * world.step
    half = world.half_width[world.sample_of(at)]

    assert world.surface_at(world.place(at, 0.0)[0]) is Surface.TRACK
    assert world.surface_at(world.place(at, half + 0.5)[0]) is Surface.KERB
    assert world.surface_at(world.place(at, half + 3.0)[0]) is Surface.RUNOFF
    assert world.surface_at(world.place(at, half + 14.0)[0]) is Surface.GRAVEL
    assert world.surface_at(world.place(at, half + 40.0)[0]) is Surface.BARRIER


def test_what_is_off_the_road_grips_less_than_the_road(world):
    assert Surface.TRACK.grip == 1.0
    assert Surface.KERB.grip < Surface.TRACK.grip
    assert Surface.GRASS.grip < Surface.RUNOFF.grip
    assert Surface.GRAVEL.grip < Surface.GRASS.grip


def test_the_road_is_as_wide_as_the_engine_says_it_is(world):
    """The width is not this layer's to invent: a car on the white line here is
    on the white line in the physics."""
    track = load_track("bahrain")
    for distance in (0.0, 900.0, 2400.0, 4800.0):
        expected = track.state_at(distance).track_width * 0.5
        assert world.half_width[world.sample_of(distance)] == pytest.approx(expected)


def test_a_road_that_changes_width_moves_its_edges_with_it():
    """A circuit whose width varies has to have edges that vary with it, or a
    car is on the road in the physics and on the grass in the picture."""
    from f1_race_engine.world.geometry import project_polyline

    line = tuple(Vec2(float(i) * 10.0, 0.0) for i in range(6))
    widths = (4.0, 5.0, 6.0, 7.0, 8.0, 9.0)
    edge = project_polyline(line, widths)

    across = [abs(edge[i].y - line[i].y) for i in range(len(line))]
    assert across == pytest.approx(list(widths))
    assert across[-1] > across[0], "the edge widens with the road"


# -- placing a car -------------------------------------------------------------


def test_a_car_on_the_line_is_on_the_road(world):
    for distance in (0.0, 1200.0, 3300.0, 5000.0):
        point, _ = world.place(distance, 0.0)
        assert world.surface_at(point) is Surface.TRACK


def test_offsetting_a_car_moves_it_across_the_road_not_along_it(world):
    """Left is positive, the same sense the race records a car's place in."""
    middle, heading = world.place(1200.0, 0.0)
    left, _ = world.place(1200.0, 3.0)

    across = Vec2(math.cos(heading), math.sin(heading)).left
    assert (left - middle).dot(across) == pytest.approx(3.0)
    assert (left - middle).length == pytest.approx(3.0)


def test_a_lap_wraps(world):
    start, _ = world.place(0.0, 0.0)
    round_again, _ = world.place(world.length, 0.0)

    assert (start - round_again).length < 1.0


# -- the pit lane --------------------------------------------------------------


def test_the_pit_lane_leaves_the_road_and_comes_back(world):
    """It is a road beside the road: away from the circuit in the middle, and
    against it at both ends."""
    path = world.pit_path
    assert len(path) > 8

    def off_road(point: Vec2) -> float:
        index, across = world._nearest(point)
        return abs(across) - world.half_width[index]

    assert off_road(path[0]) < off_road(path[len(path) // 2])
    assert off_road(path[-1]) < off_road(path[len(path) // 2])
    assert off_road(path[len(path) // 2]) > 5.0, "the lane is clear of the circuit"


# -- bodies and contact --------------------------------------------------------


def test_a_car_is_a_rectangle_the_size_of_a_car():
    car = CarBody(1, Vec2(0.0, 0.0), 0.0)
    corners = car.corners()

    assert (corners[0] - corners[3]).length == pytest.approx(CAR_WIDTH)
    assert (corners[0] - corners[1]).length == pytest.approx(CAR_LENGTH)


def test_a_turned_car_turns_its_shape_with_it():
    car = CarBody(1, Vec2(0.0, 0.0), math.pi / 2)
    front = car.corners()[0]

    assert front.y > 2.0, "pointing up the page, so the nose is above the middle"
    assert abs(front.x) < 1.5


def test_two_cars_a_road_apart_are_not_touching():
    a = CarBody(1, Vec2(0.0, 0.0), 0.0)
    b = CarBody(2, Vec2(0.0, 4.0), 0.0)

    assert overlap(a, b) is None


def test_two_cars_nose_to_tail_are_not_touching():
    a = CarBody(1, Vec2(0.0, 0.0), 0.0)
    b = CarBody(2, Vec2(8.0, 0.0), 0.0)

    assert overlap(a, b) is None


def test_two_cars_in_the_same_place_are_touching_and_can_be_parted():
    a = CarBody(1, Vec2(0.0, 0.0), 0.0, speed=70.0)
    b = CarBody(2, Vec2(0.0, 1.2), 0.0, speed=70.0)

    contact = overlap(a, b)
    assert contact is not None
    assert contact.depth == pytest.approx(CAR_WIDTH - 1.2)

    resolve(a, b, contact)
    assert a.position.y < 0.0 < b.position.y, "pushed apart, not together"
    assert a.speed < 70.0 and b.speed < 70.0, "a contact costs speed"
    assert a.damage > 0.0 and b.damage > 0.0


def test_a_contact_turns_a_car_away_from_what_it_hit():
    """Turning them into each other is how two cars weld together and never
    come apart again."""
    a = CarBody(1, Vec2(0.0, 0.0), 0.0, speed=70.0)
    b = CarBody(2, Vec2(0.0, 1.2), 0.0, speed=70.0)

    resolve(a, b, overlap(a, b))

    assert a.heading < 0.0, "pushed to the right, so it points right"
    assert b.heading > 0.0


def test_a_wall_is_only_hit_when_the_car_reaches_it():
    """Measured along the direction the wall is, not as a circle round the car
    -- a car running parallel reaches its half width towards it, not its
    diagonal."""
    wall = (Vec2(-50.0, 4.0), Vec2(50.0, 4.0))

    clear = CarBody(1, Vec2(0.0, 2.5), 0.0)
    touching = CarBody(2, Vec2(0.0, 3.4), 0.0)

    assert against_wall(clear, wall) is None
    assert against_wall(touching, wall) is not None


def test_a_wall_costs_more_than_another_car():
    into_wall = CarBody(1, Vec2(0.0, 3.5), 0.0, speed=80.0)
    into_car = CarBody(2, Vec2(0.0, 0.0), 0.0, speed=80.0)
    other = CarBody(3, Vec2(0.0, 1.5), 0.0, speed=80.0)

    resolve(into_wall, None, against_wall(into_wall, (Vec2(-50.0, 4.0), Vec2(50.0, 4.0))))
    resolve(into_car, other, overlap(into_car, other))

    assert into_wall.damage > into_car.damage


# -- the world ----------------------------------------------------------------


def test_a_field_spread_round_the_lap_touches_nothing(world):
    race = World(track=world)
    for index in range(20):
        race.drive(index + 1, 260.0 * index, (index % 5 - 2) * 1.5, 70.0)

    assert race.step(0.1) == []
    assert all(body.on_track for body in race.bodies.values())


def test_two_cars_put_in_the_same_place_end_up_apart(world):
    race = World(track=world)
    race.drive(1, 1200.0, -0.5, 70.0)
    race.drive(2, 1200.0, 0.5, 70.0)

    events = race.step(0.1)

    assert [event.kind for event in events] == ["car"]
    assert overlap(race.bodies[1], race.bodies[2]) is None
    assert all(body.on_track for body in race.bodies.values()), "not flung off"


def test_a_contact_is_charged_once_however_many_passes_it_takes(world):
    """Separating two cars turns them, and turning them can put them back
    together -- so the solver runs again.  It must not bill again."""
    race = World(track=world)
    race.drive(1, 1200.0, -0.5, 70.0)
    race.drive(2, 1200.0, 0.5, 70.0)

    events = race.step(0.1)

    assert len(events) == 1


def test_leaving_the_road_is_noticed(world):
    at = next(i for i, corner in enumerate(world.corners) if corner) * world.step
    half = world.half_width[world.sample_of(at)]

    race = World(track=world)
    race.drive(1, at, half + 14.0, 40.0)
    race.step(0.1)

    assert race.bodies[1].on_track is False
    assert race.surface_under(1) is Surface.GRAVEL


# -- it has to do the same thing twice -----------------------------------------


def test_the_same_world_is_built_twice(world):
    again = build_world(load_track("bahrain"))

    assert [p.to_tuple() for p in again.centre] == [p.to_tuple() for p in world.centre]
    assert again.half_width == world.half_width
    assert [w.points[0].to_tuple() for w in again.barriers] == [
        w.points[0].to_tuple() for w in world.barriers
    ]


def test_the_same_inputs_step_to_the_same_world(world):
    def run() -> list[tuple[float, float, float, float]]:
        race = World(track=world)
        for index in range(12):
            race.drive(index + 1, 1200.0 + index * 2.4, (index % 3 - 1) * 0.9, 68.0)
        race.step(0.1)
        return [
            (
                race.bodies[n].position.x,
                race.bodies[n].position.y,
                race.bodies[n].heading,
                race.bodies[n].damage,
            )
            for n in sorted(race.bodies)
        ]

    assert run() == run()


def test_the_broadphase_gives_the_same_pairs_in_the_same_order():
    """A set iterated in whatever order it likes is how a replay stops
    replaying."""
    def pairs() -> list[tuple[int, int]]:
        grid = Grid(cell=10.0)
        for index in range(12):
            grid.add(Vec2(index * 3.0, (index % 4) * 2.0), index)
        return list(grid.pairs())

    assert pairs() == pairs()


# -- the grid is the reason it is fast -----------------------------------------


def test_the_grid_finds_what_is_near_and_ignores_what_is_not():
    grid = Grid(cell=10.0)
    grid.add(Vec2(0.0, 0.0), 1)
    grid.add(Vec2(5.0, 5.0), 2)
    grid.add(Vec2(500.0, 500.0), 3)

    near = set(grid.near(Vec2(1.0, 1.0)))
    assert {1, 2} <= near
    assert 3 not in near


def test_the_closest_point_on_a_segment_is_on_it():
    start, end = Vec2(0.0, 0.0), Vec2(10.0, 0.0)

    assert closest_point_on_segment(Vec2(5.0, 5.0), start, end).to_tuple() == (5.0, 0.0)
    assert closest_point_on_segment(Vec2(-5.0, 1.0), start, end).to_tuple() == (0.0, 0.0)
    assert closest_point_on_segment(Vec2(50.0, 1.0), start, end).to_tuple() == (10.0, 0.0)
